### ISSUE TITLE
Catalogue as SDK/Extensions development

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/emif-fb#840]
This idea is still for discussion but the idea is to have the capability to develop extension to the Catalogue and also create the capability to use the questionnaire in third-party applications as Workflow management. 

Before doing this task, it need to be discussed here.

**Comment by bastiao** [comment]
Following some internal discussions, we decided to develop an API for interaction with the Catalogue system (including add new extensions for the dashboard).

The main idea will be allow to register new extensions that could be dynamically included in dashboard, or any menu (we need to come up with a decision regarding the hooks (web interface) that will be included. 
Until now, we come across two possible ways to integrate it (external applications in dashboard):
- Widgets: an API that can be described to integrate third-party components. 
- IFrame API for developers: only by URL and maybe included with iframe. 

Moreover, the SDK (in js) should provide a capability to store metadata (key, value) - or json. 


Over the top, the admin users (or maybe in the developers group) should be able to register new services. It should be validate the API interface to avoid errors or wrong integrations.

**Comment by bastiao** [comment]
Another interested topic to insert, will be the capability to create a hook to insert new dashboards for the fingerprint space. Taking it in consideration, we may be able to put  ACHILLES WEB working as a plugin.

Maybe it is a nice point to discuss next week.

**Comment by bastiao** [comment]
Followed the discussion with @ribeiroct and @jloliveira the plugin Architecture of the Catalogue will have the following components:

- Global statistics for the main entry points (ex. of widgets could be Tag Cloud)
- Fingerprint Extensions: Capability to integrate components of visualisation in the template (ex. ACHILLES) 
- Third-party applications could be integrated as Iframe (Knowledge Objects Library, ECH4CR Query Builder- Real time query, Workflow management, etc. ) 

The users with belong to the group *Developer* will be able to register their plugins and need to choose one of the Categories. The load/unload plugins could be implemented in Django-admin application (extension, similar to user statistics) - again, only users belong to the *Developer* group will be available for. They will have capability to upload the Javascript code to our server or load the script from external server. 

It is also important to define the structure of a widget component for Global:

```
// Examples of possible inputs for confs: {“name”: “widgetname", “width”: 10, “height”: 20, "pos_x": 1, “pos_y”20”}
// This kind of information should be provided in a separated JSON files, for instance: SampleGlobalWidget.js and SampleGlobalWidget.json 
var SampleGlobalWidget = function SampleGlobalWidget(confs){

SampleGlobalWidget._base.apply(this, [confs.widgetname, “My Sample", confs.width, confs.height, confs.pos_x, confs.pos_y]);

}.inherit(DashboardWidget).addToPrototype({

     __init : function(gridster, parent){
    }
    setGlobalProxy : function(globalProxy){
           // Do whatever you want here. For instance:
           globalProxy.databaseSchemas();
        
    }

});

```

Example of structure plugin for Fingerprint Extension: 

```
// Examples of possible inputs for confs: {“name”: “widgetname", “width”: 10, “height”: 20}
// This kind of information should be provided in a separated JSON files, for instance: SampleGlobalWidget.js and SampleGlobalWidget.json 
var SampleFingerprintWidget = function SampleFingerprintWidget(confs){

SampleFingerprintWidget._base.apply(this, [confs.widgetname, “My Sample", confs.width, confs.height]);

}.inherit(FingerprintWidget).addToPrototype({

     __init : function(gridster, parent){
    },
    setGlobalProxy : function(globalProxy){
           // Do whatever you want here. For instance:
           globalProxy.databaseSchemas();
        
    },

     
setFingerprintProxy : function(fingerprintProxy){
           // Do whatever you want here. For instance:
           fingerprintProxy.getFingerprintUID();
        
    }

});

```

Finally, but not least, it is necessary to define the API of the GlobalProxy and FingerprintProxy. The set methods will be called in the instantiation of the module (runtime, of course). 

*GlobalProxy*: 

- databaseSchemas()
- getProfileInformation()
- getFingerprints(Schema)
- query(query, schema)
- advancedQuery(query, schema) 
- getStore() - CRUD + File Upload/Retrieve

*FingerprintProxy*: 

- getFingerprintUID();
- getSchema()
- getAnswers()
- getStore(fingerprintID) - CRUD + File Upload/Retrieve

Let’s keep the state of the discussion in the loop!

**Comment by ribeiroct** [comment]
The basics are done. So is the basic documentation.

We may overtime add new methods to the proxies, and improve plugin capabilities (which should have they're own issue), but i think we can close this issue.
