### ISSUE TITLE
SDK: capability to upload a set of dependencies. 

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/emif-fb#864]
For instance a zip with a set of javascript, and css to reference in extralib, extracss.

**Comment by bastiao** [comment]
@tnovo will need to upload html files also. @ribeiroct Do you think that it is possible to add?

**Comment by ribeiroct** [comment]
HTML files for rendering proposes in a template like in angular or react.? I guess that would be possible.  

Full HTML pages with script tags and such...  No.  The plug-ins must be javascript  and conforme to their container and a plug-in lifestyle. 

I've been thinking how to implement the dependencies upload and something like the documents api api should do. With files staying on a Mongo db and an file URL being provided. That way the plug-in could directly reference the file in the widget. Like images, etc

**Comment by ribeiroct** [comment]
A Better solution for having a plug-in take a whole HTML file in would be doing a plug-in wrapper that included it through an iframe.

**Comment by bastiao** [comment]
@ribeiroct yes, it will be html to be loaded by ajax, (or similar like angular or react). So only need to have a way to provide the html files or any other file, for instance, images? 

iFrame could also another alternative solution for fingerprint plugin. Can we implement both in order to release a first alpha of developers plugin?

**Comment by ribeiroct** [comment]
Well the system as it is already allows the development of iframe plugins but i guess i could make an class to ease it. So the plugin inherits from it instead of the normal plugin base.

 But it as easy as adding the iframe tag with context.append method...

**Comment by ribeiroct** [comment]
I will get into the dependencies backend monday.

**Comment by bastiao** [comment]
you're also right. capability to have html contents to be loaded will be enough.

**Comment by ribeiroct** [comment]
Done and in pull.

**Comment by tnovo** [comment]
1) Capability of removing dependencies (added by mistake) would be nice :)

2) Dependencies like jquery/requireJS/bootstrap/etc could be already available without the need to upload them each time. (see 4)

3) I was thinking about the possibility of including code mantained in github repositories...
We could include the github repo / branch and it would automatically clone it and be available for use, which I think it's better for mass upload

4) Also, when adding multiple files we could have a combobox saying if it's an external library (mantained by third-party), E.g: jQuery, or if it's code developed for this project. This is good because an external library can be added to our main library dinamically (first developer who would need a library would upload it and it would be available to future developers automatically)

**Comment by ribeiroct** [comment]
jquery and boostrap are already available without any necessity to include them (i think that is explained in the sdk documentation).

Requirejs still isn't because we are not using it anywhere yet, but could be included i guess.

**Comment by bastiao** [comment]
1. For now, we will not track the version of dependencies. So it will like a global repository by developer. Other solution will be increase a lot the complexity. 

2. Include require.js is something that we need to evaluate globally, not only for SDK. It should be a great effort no? If you include for SDK, it will management only these dependencies right? Do you think that it can works fine for our require.js pilot test?

3. True! 

4. It's better to keep in the sandbox as @ribeiroct. But we still may have problems with different versions with different plugins in the future, right?

**Comment by ribeiroct** [comment]
1. We already track the version of dependencies on the current version of the system(The user just doesnt see it).

2. Yes for now it would only be for the dependencies.

3. Yeah we can allow zips.

4. If the plugins attach themselves directly to the dom, yes. It doesn't happen in all plugins, but the ones that do it may be a problem eventually.

**Comment by bastiao** [comment]
1. Done. 

2. Perfect. Can we include in the related PR?

3. Perfect. It will be included in PR?

4. Yah, I understood the problem. Sadly, but it is the libraries problem. The things are starting to change, I believe.

**Comment by ribeiroct** [comment]
Yeah i probably can do it today.

**Comment by ribeiroct** [comment]
I fixed 1) and 3)

2) Couldn't be fixed because require.js messes every single script tag include (since require.js presumes everything will be imported through it). We would need to port all js code to include this which is a gigantic task since we have a lot of js code, and error-prone.
