### ISSUE TITLE
SDK: dashboard is empty

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/emif-fb#872]
Now when I open the dashboard is empty and need to reset to appear widgets.

Do you think normal users will have the problem after release the feature?

**Comment by bastiao** [comment]
Also, there are cache in components and sometimes only when I reset I can see them in Fingerprint tabs.
It is quite weird.

**Comment by ribeiroct** [comment]
Could be related with the solved #877

**Comment by bastiao** [comment]
@ribeiroct is it solved?

**Comment by ribeiroct** [comment]
I think so
