### ISSUE TITLE
Avoid to have EmailTemplate in a clear setup 

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/emif-fb#878]
Avoid to run it in a clear installation. Why we need to have it? 
```
cat ../confs/newsletter/newsletter_templates.sql | python manage.py dbshell
```

**Comment by ribeiroct** [comment]
We would initial an initial data script for django.  Possible I think.

**Comment by bastiao** [comment]
it could work like a fixture or something like that, otherwise we need to add it in manual.

**Comment by ribeiroct** [comment]
I made the fixtures, which raised me a question, wouldn't be nice to do this for questionnaires schemas ? And maybe for some users, so we dont have to create an superuser and add an EmifProfile for this said user.,
