### ISSUE TITLE
Fingerprint Plugin - Capability to check ownership of fingerprint

### ISSUE THREAD

**Issue by tnovo** [bioinformatics-ua/emif-fb#912]
Fingerprint Plugin should know if client is the owner of the fingerprint associated with the plugin

**Comment by ribeiroct** [comment]
The information already can be infered through the Proxies.

    var gp = GlobalProxy.getInstance();
    var fp = FingerprintProxy.getInstance();

    var is_owner = (gp.getProfileInformation().email === fp.getFingerprintUID().owner);

**Comment by tnovo** [comment]
hum, it would be good to have a wrapper around that (easier for devs) but that should work

**Comment by ribeiroct** [comment]
Actually i was oversimplifying it. The calls upon the proxies obviously are webservice calls which must be made asynchronously, so they return promises, not the actual object immediately. So the correct code would be.

    var gp = GlobalProxy.getInstance();
    var fp = FingerprintProxy.getInstance();
    
    gp.getProfileInformation().then(function(profile){
        gp.getFingerprintUID().then(function(fingerprint){
                 var is_owner = (profile.email === fingerprint.owner);
        });
    });

**Comment by bastiao** [comment]
yes, promises is the way.

**Comment by ribeiroct** [comment]
@bastiao : Can this be closed ?
